export * from "./NotFound";
export * from "./Cart";
export * from "./Home";
export * from "./Catalog";
export * from "./ProductCatalog";
export * from "./CardProduct";
export * from "./AboutСompany";
export * from "./PaymentAndDelivery";
export * from "./Reviews";
